version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    networks:
      - crm-nw
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    container_name: backend-app
    env_file: 
      - ./backend/.env
        #ports:
        # - 5000:5000
    networks:
      - crm-nw
    depends_on: 
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /
    restart: always
    container_name: frontend-app
    networks:
      - crm-nw
    ports:
      - 8080:80
    depends_on:
      - backend


networks:
  crm-nw:
    driver: bridge

volumes:
  mongo-data:

